name: ghibli
channels:
  - pytorch
  - defaults
dependencies:
  - cudatoolkit
  - pip>=21.*
  - pytest
  - python=3.9.*
  - pytorch>=1.11.*
  - pyyaml
  - torchvision>=0.12.*
  - pip:
    - scenedetect
    - flake8
